### ISSUE TITLE
Замечания от 24.05.2017

### ISSUE THREAD

**Issue by QuickNickKoenig** [enigm777/GithubPersonLoader#1]
GithubPersonActivity
- Дублирование кода. Выдели метод, который проставляет данные из GithubPerson на вьюхи. Вызывай его из onCreate() и onLoadFinished().
- Посмотри в сторону атрибута TextView freezesText. В таком случае тебе не потребуется проставлять данные в onCreate().
- Вообще, тебе и не придётся беспокоиться о сохранении состояния в активити. Лоадер тебе и так данные возвратит при пересоздании активити.

GithubPersonParser:
- Раздели парсер и получение данных.

**Comment by enigm777** [comment]
Убрал дублирование кода.
Решил проблему с сохранением состояния активити, с помощью лоадера.
Выделил получение данных из сети в парсере в отдельный метод
